apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers: 
    - name: client-container
      image: k8stest/sshd:test
      ports: 
        - containerPort: 22
          hostPort: 1314
